apiVersion: v1
kind: Service
metadata:
  name: {{ include "fauxpilot.fullnameTriton" . }}-http
  labels:
    {{- include "fauxpilot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000

  selector:
    {{- include "fauxpilot.selectorLabelsTriton" . | nindent 4 }}
