apiVersion: v1
kind: Service
metadata:
  name: {{ include "fauxpilot.fullnameTriton" . }}-metrics
  labels:
    {{- include "fauxpilot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    {{- include "fauxpilot.selectorLabelsTriton" . | nindent 4 }}
