apiVersion: v1
kind: ConfigMap
metadata:
  name: fauxpilot-s3
data:
  config.json: |
                {
                "version": "10",
                "aliases": {
                  "gcs": {
                          "url": "https://storage.googleapis.com",
                          "accessKey": "YOUR-ACCESS-KEY-HERE",
                          "secretKey": "YOUR-SECRET-KEY-HERE",
                          "api": "S3v2",
                          "path": "dns"
                  },
                  "local": {
                          "url": "http://localhost:9000",
                          "accessKey": "",
                          "secretKey": "",
                          "api": "S3v4",
                          "path": "auto"
                  },
                  "play": {
                          "url": "https://play.min.io",
                          "accessKey": "",
                          "secretKey": "",
                          "api": "S3v4",
                          "path": "auto"
                  },
                  "s3": {
                          "url": "{{ .Values.s3.endpoint }}",
                          "accessKey": "{{ .Values.s3.access_key_id }}",
                          "secretKey": "{{ .Values.s3.secret_access_key }}",
                          "api": "S3v4",
                          "path": "dns"
                  }
                 }
                }
