apiVersion: v1
kind: Service
metadata:
  name: {{ include "fauxpilot.fullnameTriton" . }}
  labels:
    {{- include "fauxpilot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8001
      targetPort: 8001

  selector:
    {{- include "fauxpilot.selectorLabelsTriton" . | nindent 4 }}
